name: Bump

on:
  workflow_dispatch:
  schedule:
    - cron: 0 6 * * *

jobs:
  bump-pixi:
    name: Reference latest Pixi version in README
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Assert latest pixi version is mentioned in README
        id: bump
        run: |
          set -euo pipefail
          latest_version="$(gh repo view --json latestRelease prefix-dev/pixi | jq -r '.latestRelease.tagName')"
          echo latest-version=$latest_version >> $GITHUB_OUTPUT
          latest_version_no_v=${latest_version#v}
          sed -i "s/ARG PIXI_VERSION=.*/ARG PIXI_VERSION=$latest_version_no_v/" Dockerfile
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: octo-sts/action@f603d3be9d8dd9871a265776e625a27b00effe05 # v1.1.1
        id: octo-sts
        with:
          scope: ${{ github.repository }}
          identity: write

      - name: Create pull request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        if: github.ref_name == 'main'
        with:
          token: ${{ steps.octo-sts.outputs.token }}
          commit-message: Bump pixi version to ${{ steps.bump.outputs.latest-version }}
          title: Bump pixi version to ${{ steps.bump.outputs.latest-version }}
          labels: enhancement
          branch: bump-pixi-${{ steps.bump.outputs.latest-version }}
